---
title: "Stat-495 Initial Proposal"
author: "Emily Ye & Shukry Zablah"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

1. Team Name: Come up with a team name for your group.

2. Title: The title of your project

3. Purpose: Describe the general topic/phenomenon you want to explore, as well some carefully considered questions that you hope to address. You should make an argument motivating your work. Why should someone be interested in what you are doing? What do you hope people will learn from your project?


4. Data: As best you can, describe where you will find your data, and what kind of data it is. Will you
be working with spatial data in shapefiles? Will you be accessing an API to a live data source? Be as
specific as you can, listing URLs and file formats if possible.


5. Variables: List, and briefly describe, each variable that you plan to incorporate. If you can, be specific
about units, scale, etc.


6. Model: What response variable will you be aiming to predict? What model are you thinking about
using? Note that the model doesn't have to be at the center of the project, but you need to have one.



7. End Product: Describe what you hope to deliver as a final product. Will it be a Shiny application that will be posted on the Internet (dynamic visualizations are strongly encouraged)? Will it be a GoogleMaps mash-up? Will it be a paper that draws some statistical conclusions and uses the model to make some predictions? Will it be a combination of these or other deliverables?