---
title: "Mapping Wineries"
output: pdf_document
---

```{r}
options(crayon.enabled = FALSE)
```

```{r}
library(tidyverse)
library(leaflet)
```

```{r}
Wine <- read_csv("../data/geocoded.csv",
                 col_types = cols(
                     id = col_double(),
                     country = col_character(),
                     description = col_character(),
                     designation = col_character(),
                     points = col_double(),
                     price = col_double(),
                     province = col_character(),
                     region_1 = col_character(),
                     region_2 = col_character(),
                     taster_name = col_character(),
                     taster_twitter_handle = col_character(),
                     title = col_character(),
                     variety = col_character(),
                     winery = col_character(),
                     address = col_character(),
                     lon = col_double(),
                     lat = col_double()
                 ))

Wine %>% glimpse()
```

```{r}
Wine %>%
    leaflet() %>%
    addTiles() %>%
    #addMarkers(clusterOptions = markerClusterOptions())
    addCircles()
```
