---
title: "Text analysis"
author: "YZ Analytics"
date: ""
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(dplyr)
library(tidytext)
library(forcats)
```

Following https://www.tidytextmining.com/tfidf.html

```{r}
wine_words <- Wine %>%
  unnest_tokens(word, description) %>%
  count(variety, word, sort = TRUE)
```

```{r}
plot_wine <- wine_words %>%
  bind_tf_idf(word, variety, n) %>%
  mutate(word = fct_reorder(word, tf_idf)) %>%
  mutate(variety = factor(variety, levels = c("Pinot Noir",
                                            "Cabernet Sauvignon", 
                                            "Chardonnay",
                                            "Red Blend")))

plot_wine %>% 
  group_by(variety) %>% 
  top_n(15, tf_idf) %>% 
  ungroup() %>%
  mutate(word = reorder(word, tf_idf)) %>%
  ggplot(aes(word, tf_idf, fill = variety)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~variety, ncol = 2, scales = "free") +
  coord_flip()
```


