---
title: "Stat-495 Revised Proposal"
author: "Emily Ye & Shukry Zablah"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
library(rtweet)
# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

**Team Name:** YZ Analytics

**Title:** Another Glass, Please: Creating a Virtual Sommelier

**Purpose:** Purchasing wine can be overwhelming with the sheer number of choices there are, whether they be on a restaurant's wine menu, in liquor stores, or wineries. In this project, we aim to understand the features of what makes a good wine and predict the quality of wine from its description. Our project is applicable to both newly exploring wine drinkers and experienced wine enthusiasts alike. Non-wine drinkers will be able to know what makes a good wine, and wine drinkers will be able to explore and discover new wine varieties to try.

**Data:** We will be working with Kaggle's wine review data, found here: https://www.kaggle.com/zynicide/wine-reviews (Thoutt, 2017). There are close to 130,000 wine reviews.

**Variables:**

Variable descriptions from the data set:

country - The country that the wine is from
description - A few sentences from a sommelier describing the wine's taste, smell, look, feel, etc.
designation - The vineyard within the winery where the grapes that made the wine are from
points - The number of points WineEnthusiast rated the wine on a scale of 1-100 (though they say they only post reviews for wines that score >=80)
price - The cost for a bottle of the wine
province - The province or state that the wine is from
region_1 - The wine growing area in a province or state (ie Napa)
region_2 - Sometimes there are more specific regions specified within a wine growing area (ie Rutherford inside the Napa Valley), but this value can sometimes be blank
variety - The type of grapes used to make the wine (ie Pinot Noir)
winery - The winery that made the wine

**Model:** We aim to create a model to predict the quality of wine (based on the number of points it received from WineEnthusiast) from its description. We plan to create our model using the random forest method. 

**End Product:** We aim to create a Virtual Sommelier with dynamic visualizations that provides wine recommendations based on different filters. For example, we envision an interactive map that will allow users to choose a country from which the wine is made. Additionally, we can add the most important features found from the random forest model to serve as filters for the wine recommendations.

### References

Thoutt, Zack. (2017). "Wine Reviews." Kaggle. https://www.kaggle.com/zynicide/wine-reviews